version: "3.8"

services:
  api:
    # image: python:3.8
    container_name: "composer-teste"
    build: .
    #   context: /app
    # volumes:
    # - .:/app
    ports:
      - "8000:8000"
    hostname: "localhost"
    depends_on:
      - db
    tty: true

  db:
    image: postgres:14-alpine
    container_name: "postgres"
    hostname: "localhost"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "5433:5432"
    tty: true